ccflags-y += -I$(srctree)/drivers/misc/mediatek/smi
ccflags-y += -I$(srctree)/drivers/misc/mediatek/cmdq
mtk-vcu-y += mtk_vcu.o

obj-$(CONFIG_VIDEO_MEDIATEK_VCU) += mtk_vcu.o
ccflags-y += -I$(srctree)/arch/arm
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat
